// <auto-generated />
using Luley_Integracion_Net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Luley_Integracion_Net.Migrations
{
    [DbContext(typeof(LuleyDbContext))]
    partial class LuleyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Luley_Integracion_Net.Models.DeliveryNoteDataModel", b =>
                {
                    b.Property<string>("nroRemito")
                        .HasColumnType("text");

                    b.Property<string>("codArticulo")
                        .HasColumnType("text");

                    b.Property<int>("cantidadRemitida")
                        .HasColumnType("integer");

                    b.Property<int>("estadoRemito")
                        .HasColumnType("integer");

                    b.HasKey("nroRemito", "codArticulo");

                    b.ToTable("DeliveryNotesDataModel");
                });
#pragma warning restore 612, 618
        }
    }
}
